import { HashMap } from "./hashmapConstructor.mjs";

const test = new HashMap();
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("kite", "pink");
test.set("lion", "golden");
test.set('lion', 'aslan');
test.set('hat', 'sombrero');
test.set('apple', 'brown');
test.set('banana', 'bugs bunny')
test.set("moon", "silver");
console.log(test.entries());
console.log(test.length());
console.log(test.capacity);
test.set('moon', 'full');
test.set('banana', 'please fucking work');
test.set('apple', 'red');
test.set('hat', 'barbados');
test.set('lion', 'simba');
test.set('kite', 'box');
test.set('jacket', 'leather');
test.set('ice cream', 'cookies n\' cream');
test.set('grape', 'seedless');
test.set('frog', 'crazy');
test.set('elephant', 'memory');
test.set('dog', 'man\'s best friend');
test.set('carrot', 'stick');
console.log(test.entries());
console.log(test.length());
console.log(test.capacity);